using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General information about the assembly is controlled by the following
// attributes. Modifying these values may change
// the information associated with the assembly.
[assembly: AssemblyTitle("ZpenSample")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("ZpenSample")]
[assembly: AssemblyCopyright("Copyright ©  2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly
// not visible to COM components. If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true for that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("29f371ea-58e8-46a7-8470-12ea57165461")]

// A GUID (Globally Unique Identifier) is a unique identifier that is generated by a computer system or software algorithm to ensure that a particular entity, such as a file, database record, or component, is uniquely identified in a global context. GUIDs are typically represented as a 128-bit value, often displayed as a hexadecimal string separated by hyphens, such as "550e8400-e29b-41d4-a716-446655440000".

// GUIDs are useful in scenarios where unique identification is required, especially in distributed systems where multiple entities need to be uniquely identified without the risk of collision (i.e., two different entities having the same identifier). They are commonly used in various technologies such as COM (Component Object Model), .NET framework, databases, and other software systems.
// Version information for the assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

// using System.Reflection;
// using System.Runtime.CompilerServices;
// using System.Runtime.InteropServices;

// // 有关程序集的一般信息由以下
// // 控制。更改这些特性值可修改
// // 与程序集关联的信息。
// [assembly: AssemblyTitle("ZpenSample")]
// [assembly: AssemblyDescription("")]
// [assembly: AssemblyConfiguration("")]
// [assembly: AssemblyCompany("")]
// [assembly: AssemblyProduct("ZpenSample")]
// [assembly: AssemblyCopyright("Copyright ©  2019")]
// [assembly: AssemblyTrademark("")]
// [assembly: AssemblyCulture("")]

// // 将 ComVisible 设置为 false 会使此程序集中的类型
// //对 COM 组件不可见。如果需要从 COM 访问此程序集中的类型
// //请将此类型的 ComVisible 特性设置为 true。
// [assembly: ComVisible(false)]

// // 如果此项目向 COM 公开，则下列 GUID 用于类型库的 ID
// [assembly: Guid("29f371ea-58e8-46a7-8470-12ea57165461")]

// // 程序集的版本信息由下列四个值组成: 
// //
// //      主版本
// //      次版本
// //      生成号
// //      修订号
// //
// // 可以指定所有值，也可以使用以下所示的 "*" 预置版本号和修订号
// // 方法是按如下所示使用“*”: :
// // [assembly: AssemblyVersion("1.0.*")]
// [assembly: AssemblyVersion("1.0.0.0")]
// [assembly: AssemblyFileVersion("1.0.0.0")]
